import { SidebarGroupType } from '@/types/sidebar';
import {
  ArrowRightLeft,
  BriefcaseBusiness,
  ChartLine,
  CircleDollarSign,
  Coins,
  FileClock,
  HandCoins,
  Handshake,
  Home,
  List,
  Nfc,
  Plus,
  Repeat,
  UserPlus,
  UserRoundPen,
  Users,
  WalletCards,
} from 'lucide-react';

const ClientGroups: SidebarGroupType[] = [
  {
    title: 'Home',
    url: '/c',
    icon: Home,
    isActive: false,
    userType: 'client',
    privileges: [],
    items: undefined,
  },
  {
    title: 'Transactions',
    url: '/c/transactions',
    icon: ArrowRightLeft,
    isActive: false,
    userType: 'client',
    privileges: [],
    items: [
      {
        title: 'Overview',
        url: '/c/transactions',
        icon: List,
        privileges: [],
      },
      {
        title: 'New Payment',
        url: '/c/transactions/new-payment',
        icon: Nfc,
        privileges: [],
      },
      {
        title: 'New Transfer',
        url: '/c/transactions/transfer',
        icon: HandCoins,
        privileges: [],
      },
      {
        title: 'Transfer History',
        url: '/c/transactions/transfer-history',
        icon: List,
        privileges: [],
      },
    ],
  },
  {
    title: 'Loans',
    url: '/c/loans',
    icon: HandCoins,
    isActive: false,
    userType: 'client',
    privileges: [],
    items: [
      {
        title: 'Overview',
        url: '/c/loans',
        icon: List,
        privileges: [],
      },
      {
        title: 'Request',
        url: '/c/loans/request',
        icon: Plus,
        privileges: [],
      },
    ],
  },
  {
    title: 'Contacts',
    url: '/c/contacts',
    icon: Users,
    isActive: false,
    userType: 'client',
    privileges: [],
    items: [
      {
        title: 'Manage',
        url: '/c/contacts',
        icon: List,
        privileges: [],
      },
    ],
  },
  {
    title: 'Exchange',
    url: '/c/exchange',
    icon: Repeat,
    isActive: false,
    userType: 'client',
    privileges: [],
    items: undefined,
  },
  {
    title: 'Listings',
    url: '/u',
    icon: ChartLine,
    isActive: false,
    userType: 'client',
    privileges: ['TRADE'],
  },
  {
    title: 'OTC',
    url: '/u/otc',
    icon: Handshake,
    isActive: false,
    userType: 'client',
    privileges: ['TRADE'],
    items: [
      {
        title: 'Overview',
        url: '/u/otc',
        icon: List,
        privileges: ['TRADE'],
      },
    ],
  },
];

const EmployeeGroups: SidebarGroupType[] = [
  {
    title: 'Home',
    url: '/e',
    icon: Home,
    isActive: false,
    userType: 'employee',
    privileges: [],
    items: undefined,
  },
  {
    title: 'Accounts',
    url: '/e/accounts',
    icon: Coins,
    isActive: false,
    userType: 'employee',
    privileges: [],
    items: [
      {
        title: 'Overview',
        url: '/e/accounts',
        icon: List,
        privileges: [],
      },
      {
        title: 'New',
        url: '/e/accounts/new',
        icon: Plus,
        privileges: [],
      },
    ],
  },
  {
    title: 'Clients',
    url: '/e/client',
    icon: Users,
    isActive: false,
    userType: 'employee',
    privileges: [],
    items: [
      {
        title: 'Overview',
        url: '/e/client',
        icon: List,
        privileges: [],
      },
    ],
  },
  {
    title: 'Cards',
    url: '/e/cards',
    icon: WalletCards,
    items: [
      {
        title: 'Overview',
        url: '/e/cards',
        icon: List,
        privileges: [],
      },
    ],
    isActive: false,
    userType: 'employee',
    privileges: [],
  },
  {
    title: 'Employees',
    url: '/e/employee',
    icon: BriefcaseBusiness,
    isActive: false,
    userType: 'employee',
    privileges: [],
    items: [
      {
        title: 'Overview',
        url: '/e/employee',
        icon: List,
        privileges: ['ADMIN'],
      },
      {
        title: 'New',
        url: '/e/employee/new',
        icon: UserPlus,
        privileges: ['ADMIN'],
      },
    ],
  },
  {
    title: 'Loans',
    url: '/e',
    icon: CircleDollarSign,
    isActive: false,
    userType: 'employee',
    privileges: [],
    items: [
      {
        title: 'Overview',
        url: '/e/loans',
        icon: List,
        privileges: [],
      },
      {
        title: 'Requests',
        url: '/e/loans/requests',
        icon: List,
        privileges: [],
      },
    ],
  },
  {
    title: 'Orders',
    url: '/e/orders',
    icon: FileClock,
    isActive: false,
    userType: 'employee',
    privileges: ['ADMIN', 'SUPERVISOR'],
  },
  {
    title: 'Listings',
    url: '/u',
    icon: ChartLine,
    isActive: false,
    userType: 'employee',
    privileges: ['ADMIN', 'SUPERVISOR', 'AGENT'],
  },
  {
    title: 'OTC',
    url: '/u/otc',
    icon: Handshake,
    isActive: false,
    userType: 'employee',
    privileges: ['ADMIN', 'SUPERVISOR', 'AGENT'],
    items: [
      {
        title: 'Overview',
        url: '/u/otc',
        icon: List,
        privileges: ['ADMIN', 'SUPERVISOR', 'AGENT'],
      },
    ],
  },
  {
    title: 'Actuaries',
    url: '/e/actuaries',
    icon: UserRoundPen,
    isActive: false,
    userType: 'employee',
    items: [
      {
        title: 'Overview',
        url: '/e/actuaries',
        icon: List,
        privileges: ['ADMIN', 'SUPERVISOR'],
      },
    ],
    privileges: [],
  },
  {
    title: 'Taxes',
    url: '/e/taxes',
    icon: HandCoins,
    isActive: false,
    userType: 'employee',
    privileges: ['ADMIN', 'SUPERVISOR'],
  },
];

export const ALL_GROUPS = EmployeeGroups.concat(ClientGroups);
