export const mockEmployees = [
  // {
  //   id: 1,
  //   first_name: 'John',
  //   last_name: 'Doe',
  //   email: 'john.doe@example.com',
  //   phone_number: '123-456-7890',
  //   position: 'Software Engineer',
  //   active: true,
  // },
  // {
  //   id: 2,
  //   first_name: 'Jane',
  //   last_name: 'Smith',
  //   email: 'jane.smith@example.com',
  //   phone_number: '987-654-3210',
  //   position: 'Product Manager',
  //   active: false,
  // },
  // {
  //   id: 3,
  //   first_name: 'John',
  //   last_name: 'Doe',
  //   email: 'john.doe@example.com',
  //   phone_number: '123-456-7890',
  //   position: 'Software Engineer',
  //   active: true,
  // },
  // {
  //   id: 4,
  //   first_name: 'Jane',
  //   last_name: 'Smith',
  //   email: 'jane.smith@example.com',
  //   phone_number: '987-654-3210',
  //   position: 'Product Manager',
  //   active: false,
  // },
  // {
  //   id: 5,
  //   first_name: 'John',
  //   last_name: 'Doe',
  //   email: 'john.doe@example.com',
  //   phone_number: '123-456-7890',
  //   position: 'Software Engineer',
  //   active: true,
  // },
  // {
  //   id: 6,
  //   first_name: 'Jane',
  //   last_name: 'Smith',
  //   email: 'jane.smith@example.com',
  //   phone_number: '987-654-3210',
  //   position: 'Product Manager',
  //   active: false,
  // },
  // {
  //   id: 7,
  //   first_name: 'John',
  //   last_name: 'Doe',
  //   email: 'john.doe@example.com',
  //   phone_number: '123-456-7890',
  //   position: 'Software Engineer',
  //   active: true,
  // },
  // {
  //   id: 8,
  //   first_name: 'Jane',
  //   last_name: 'Smith',
  //   email: 'jane.smith@example.com',
  //   phone_number: '987-654-3210',
  //   position: 'Product Manager',
  //   active: false,
  // },
  // {
  //   id: 9,
  //   first_name: 'John',
  //   last_name: 'Doe',
  //   email: 'john.doe@example.com',
  //   phone_number: '123-456-7890',
  //   position: 'Software Engineer',
  //   active: true,
  // },
  // {
  //   id: 10,
  //   first_name: 'Jane',
  //   last_name: 'Smith',
  //   email: 'jane.smith@example.com',
  //   phone_number: '987-654-3210',
  //   position: 'Product Manager',
  //   active: false,
  // },
  // {
  //   id: 11,
  //   first_name: 'John',
  //   last_name: 'Doe',
  //   email: 'john.doe@example.com',
  //   phone_number: '123-456-7890',
  //   position: 'Software Engineer',
  //   active: true,
  // },
  // {
  //   id: 12,
  //   first_name: 'Jane',
  //   last_name: 'Smith',
  //   email: 'jane.smith@example.com',
  //   phone_number: '987-654-3210',
  //   position: 'Product Manager',
  //   active: false,
  // },
  // {
  //   id: 13,
  //   first_name: 'Jane',
  //   last_name: 'Smith',
  //   email: 'jane.smith@example.com',
  //   phone_number: '987-654-3210',
  //   position: 'Product Manager',
  //   active: false,
  // },
  // {
  //   id: 14,
  //   first_name: 'Jane',
  //   last_name: 'Smith',
  //   email: 'jane.smith@example.com',
  //   phone_number: '987-654-3210',
  //   position: 'Product Manager',
  //   active: false,
  // },
  // {
  //   id: 15,
  //   first_name: 'Jane',
  //   last_name: 'Smith',
  //   email: 'jane.smith@example.com',
  //   phone_number: '987-654-3210',
  //   position: 'Product Manager',
  //   active: false,
  // },
  // {
  //   id: 16,
  //   first_name: 'Jane',
  //   last_name: 'Smith',
  //   email: 'jane.smith@example.com',
  //   phone_number: '987-654-3210',
  //   position: 'Product Manager',
  //   active: false,
  // },
  // {
  //   id: 17,
  //   first_name: 'John',
  //   last_name: 'Doe',
  //   email: 'john.doe@example.com',
  //   phone_number: '123-456-7890',
  //   position: 'Software Engineer',
  //   active: true,
  // },
  // {
  //   id: 18,
  //   first_name: 'Jane',
  //   last_name: 'Smith',
  //   email: 'jane.smith@example.com',
  //   phone_number: '987-654-3210',
  //   position: 'Product Manager',
  //   active: false,
  // },
  // {
  //   id: 19,
  //   first_name: 'John',
  //   last_name: 'Doe',
  //   email: 'john.doe@example.com',
  //   phone_number: '123-456-7890',
  //   position: 'Software Engineer',
  //   active: true,
  // },
  // {
  //   id: 20,
  //   first_name: 'Jane',
  //   last_name: 'Smith',
  //   email: 'jane.smith@example.com',
  //   phone_number: '987-654-3210',
  //   position: 'Product Manager',
  //   active: false,
  // },
  // {
  //   id: 21,
  //   first_name: 'John',
  //   last_name: 'Doe',
  //   email: 'john.doe@example.com',
  //   phone_number: '123-456-7890',
  //   position: 'Software Engineer',
  //   active: true,
  // },
  // {
  //   id: 22,
  //   first_name: 'Jane',
  //   last_name: 'Smith',
  //   email: 'jane.smith@example.com',
  //   phone_number: '987-654-3210',
  //   position: 'Product Manager',
  //   active: false,
  // },
  // {
  //   id: 23,
  //   first_name: 'John',
  //   last_name: 'Doe',
  //   email: 'john.doe@example.com',
  //   phone_number: '123-456-7890',
  //   position: 'Software Engineer',
  //   active: true,
  // },
  // {
  //   id: 24,
  //   first_name: 'Jane',
  //   last_name: 'Smith',
  //   email: 'jane.smith@example.com',
  //   phone_number: '987-654-3210',
  //   position: 'Product Manager',
  //   active: false,
  // },
  // {
  //   id: 25,
  //   first_name: 'John',
  //   last_name: 'Doe',
  //   email: 'john.doe@example.com',
  //   phone_number: '123-456-7890',
  //   position: 'Software Engineer',
  //   active: true,
  // },
  // {
  //   id: 26,
  //   first_name: 'Jane',
  //   last_name: 'Smith',
  //   email: 'jane.smith@example.com',
  //   phone_number: '987-654-3210',
  //   position: 'Product Manager',
  //   active: false,
  // },
  // {
  //   id: 27,
  //   first_name: 'John',
  //   last_name: 'Doe',
  //   email: 'john.doe@example.com',
  //   phone_number: '123-456-7890',
  //   position: 'Software Engineer',
  //   active: true,
  // },
  // {
  //   id: 28,
  //   first_name: 'Jane',
  //   last_name: 'Smith',
  //   email: 'jane.smith@example.com',
  //   phone_number: '987-654-3210',
  //   position: 'Product Manager',
  //   active: false,
  // },
  // {
  //   id: 29,
  //   first_name: 'John',
  //   last_name: 'Doe',
  //   email: 'john.doe@example.com',
  //   phone_number: '123-456-7890',
  //   position: 'Software Engineer',
  //   active: true,
  // },
  // {
  //   id: 30,
  //   first_name: 'Jane',
  //   last_name: 'Smith',
  //   email: 'jane.smith@example.com',
  //   phone_number: '987-654-3210',
  //   position: 'Product Manager',
  //   active: false,
  // },
  // {
  //   id: 31,
  //   first_name: 'John',
  //   last_name: 'Doe',
  //   email: 'john.doe@example.com',
  //   phone_number: '123-456-7890',
  //   position: 'Software Engineer',
  //   active: true,
  // },
  // {
  //   id: 32,
  //   first_name: 'Jane',
  //   last_name: 'Smith',
  //   email: 'jane.smith@example.com',
  //   phone_number: '987-654-3210',
  //   position: 'Product Manager',
  //   active: false,
  // },
  // {
  //   id: 33,
  //   first_name: 'John',
  //   last_name: 'Doe',
  //   email: 'john.doe@example.com',
  //   phone_number: '123-456-7890',
  //   position: 'Software Engineer',
  //   active: true,
  // },
  // {
  //   id: 34,
  //   first_name: 'Jane',
  //   last_name: 'Smith',
  //   email: 'jane.smith@example.com',
  //   phone_number: '987-654-3210',
  //   position: 'Product Manager',
  //   active: false,
  // },
  // {
  //   id: 35,
  //   first_name: 'John',
  //   last_name: 'Doe',
  //   email: 'john.doe@example.com',
  //   phone_number: '123-456-7890',
  //   position: 'Software Engineer',
  //   active: true,
  // },
  // {
  //   id: 36,
  //   first_name: 'Jane',
  //   last_name: 'Smith',
  //   email: 'jane.smith@example.com',
  //   phone_number: '987-654-3210',
  //   position: 'Product Manager',
  //   active: false,
  // },
];
